### ISSUE TITLE
Bug sur la page d'ajout d'abonnement - les variations ne s'ajoutent pas au panier

### ISSUE THREAD

**Issue by GMZC** [GMZC/map#6]
[Page produit abonnement](http://192.168.43.201:8888/map/produit/abonnement-annuel/)
Lorsqu'on sélectionne des options elles ne sont plus prises en compte, par ex. si tu sélectionnes "deux ans, au prochain, pour offrir" c'est "annuel, au dernier, c'est pour moi" qui s'ajoute à chaque fois.

**Comment by xseignard** [comment]
Corrigé là a283eceddc20c6a1eb4237
